#!/usr/bin/env node --no-warnings
/**
 * init-project.mts — Initialize Handoff Framework v2.0 in a project
 *
 * Creates docs/handoff/ with FSD-named templates, .handoff.config.json,
 * and an initial CO-00-MASTER_INDEX document.
 *
 * Usage: npx tsx src/init-project.mts <project-name>
 * Example: npx tsx src/init-project.mts damieus-com-migration
 */

import { copyFile, mkdir, writeFile } from 'fs/promises';
import { join } from 'path';

import { VERSION } from './version.js';
import {
  FSD_CATEGORIES,
  FSD_CATEGORY_NAMES,
  CANONICAL_DOCS_PATH,
  REQUIRED_TEMPLATES,
  RECOMMENDED_TEMPLATES,
  todayISO,
  type HandoffConfig,
} from './types.js';
import {
  log,
  fileExists,
  detectTechStack,
  getProjectVersion,
  getFrameworkRoot,
  resolveProjectDir,
  getHandoffDocsPath,
} from './utils.js';

// ─── Template Installer ─────────────────────────────────────────

interface CopyResult {
  copied: number;
  skipped: number;
}

async function copyTemplates(
  templatesDir: string,
  handoffDir: string,
  today: string,
): Promise<CopyResult> {
  const allTemplates = [...REQUIRED_TEMPLATES, ...RECOMMENDED_TEMPLATES];
  let copied = 0;
  let skipped = 0;

  for (const tpl of allTemplates) {
    // Template source: templates/v2/CO-00-MASTER_INDEX.md (no date)
    const srcFilename = `${tpl.filename}.md`;
    const srcPath = join(templatesDir, 'v2', srcFilename);

    // Output: docs/handoff/CO-00-MASTER_INDEX_2026-02-20.md (with date)
    const outFilename = `${tpl.filename}_${today}.md`;
    const outPath = join(handoffDir, outFilename);

    if (!(await fileExists(srcPath))) {
      log.dim(`  Template not found: ${srcFilename} — skipping`);
      continue;
    }

    if (await fileExists(outPath)) {
      log.warning(`  File exists: ${outFilename} (skipping)`);
      skipped++;
      continue;
    }

    await copyFile(srcPath, outPath);
    const label = tpl.required ? '🔴' : '🟡';
    log.success(`  ${label} Copied: ${outFilename}`);
    copied++;
  }

  return { copied, skipped };
}

// ─── Config Generator ────────────────────────────────────────────

function buildConfig(
  projectName: string,
  version: string,
  techStack: string[],
): HandoffConfig {
  const today = todayISO();

  return {
    projectName,
    version,
    description: '',
    techStack,
    framework: {
      version: VERSION,
      namingVersion: 'v2',
      docsPath: CANONICAL_DOCS_PATH,
      masterIndexPath: `${CANONICAL_DOCS_PATH}/CO-00-MASTER_INDEX_${today}.md`,
      tokenBudget: {
        target: 10000,
        warning: 25000,
        critical: 50000,
      },
      autoGenerated: ['CO-01-PROJECT_STATE'],
    },
    qualityGates: {
      typescript: {
        enabled: true,
        command: 'npx tsc --noEmit',
        required: true,
      },
      eslint: {
        enabled: true,
        command: 'npm run lint',
        required: true,
      },
      build: {
        enabled: true,
        command: 'npm run build',
        required: true,
      },
      routeDiscovery: {
        enabled: false,
        command: 'npm run discover:routes',
        artifact: 'e2e/fixtures/route-manifest.json',
        required: false,
      },
      devtools: {
        enabled: techStack.includes('React'),
        command: 'npm run test:devtools',
        required: techStack.includes('React'),
      },
    },
    deployment: {
      requiredGates: ['typescript', 'eslint', 'build'],
      recommendedGates: ['routeDiscovery', 'devtools'],
    },
    tokenEstimates: {},
  };
}

// ─── Master Index Generator ──────────────────────────────────────

function generateMasterIndex(
  projectName: string,
  version: string,
  techStack: string[],
  today: string,
): string {
  const reqRows = REQUIRED_TEMPLATES.map(
    (t) =>
      `| [${t.filename}_${today}.md](${t.filename}_${today}.md) | ${t.description} | ~${t.tokenBudget} | 🔴 MUST READ |`,
  ).join('\n');

  const optRows = RECOMMENDED_TEMPLATES.map(
    (t) =>
      `| [${t.filename}_${today}.md](${t.filename}_${today}.md) | ${t.description} | ~${t.tokenBudget} | 🟡 Recommended |`,
  ).join('\n');

  return `# Master Index — ${projectName}

**Project**: ${projectName}
**Version**: ${version}
**Framework**: @dabighomie/handoff-framework v${VERSION}
**Naming Version**: v2 (FSD)
**Last Updated**: ${today}

---

## Overview

[TODO: Brief project description — 1-2 sentences about what this project does]

**Tech Stack**: ${techStack.join(', ')}
**Status**: [TODO: Development / Staging / Production]

---

## Quick Start (New Agent)

1. Read this file — Navigation hub
2. Read CO-01 — Current project state & quality gates
3. Read CO-02 — Critical gotchas and must-know context
4. [TODO: Add project-specific steps]

**Estimated read time**: ~5 minutes

---

## Document Index

### FSD Categories

| Prefix | Category | Purpose |
|--------|----------|---------|
${FSD_CATEGORIES.map(
  (c) => `| ${c} | ${FSD_CATEGORY_NAMES[c]} | ${REQUIRED_TEMPLATES.find((t) => t.category === c)?.description || RECOMMENDED_TEMPLATES.find((t) => t.category === c)?.description || ''} |`,
).join('\n')}

### Required Documents

| Document | Purpose | Tokens | Priority |
|----------|---------|--------|----------|
${reqRows}

### Recommended Documents

| Document | Purpose | Tokens | Priority |
|----------|---------|--------|----------|
${optRows}

---

## Quality Gates

| Gate | Command | Status |
|------|---------|--------|
| TypeScript | \`npx tsc --noEmit\` | [TODO] |
| ESLint | \`npm run lint\` | [TODO] |
| Build | \`npm run build\` | [TODO] |

---

## Next Steps

[TODO: What should an agent work on next?]

---

**Framework**: @dabighomie/handoff-framework v${VERSION}
**Generated**: ${today}
`;
}

// ─── Main ────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const projectName = process.argv[2];

  if (!projectName) {
    log.error('Project name required');
    console.log('');
    console.log('Usage: npx tsx src/init-project.mts <project-name>');
    console.log('Example: npx tsx src/init-project.mts damieus-com-migration');
    process.exit(1);
  }

  const frameworkDir = getFrameworkRoot(import.meta.url);
  const projectDir = resolveProjectDir(frameworkDir, projectName);
  const handoffDir = getHandoffDocsPath(projectDir);
  const today = todayISO();

  log.header(`Initializing Handoff Framework v${VERSION} for: ${projectName}`);
  console.log('');

  // Step 1: Verify project exists
  if (!(await fileExists(projectDir))) {
    log.error(`Project directory not found: ${projectDir}`);
    process.exit(1);
  }
  log.success(`Found project: ${projectDir}`);

  // Step 2: Create docs/handoff/
  if (await fileExists(handoffDir)) {
    log.warning(`${CANONICAL_DOCS_PATH}/ already exists — will skip existing files`);
  } else {
    await mkdir(handoffDir, { recursive: true });
    log.success(`Created ${CANONICAL_DOCS_PATH}/`);
  }
  console.log('');

  // Step 3: Copy FSD v2 templates
  log.info('Copying FSD v2 templates...');
  const templatesDir = join(frameworkDir, 'templates');
  const { copied, skipped } = await copyTemplates(templatesDir, handoffDir, today);
  log.success(`Copied ${copied} templates, skipped ${skipped} existing`);
  console.log('');

  // Step 4: Create .handoff.config.json
  const configPath = join(projectDir, '.handoff.config.json');

  if (await fileExists(configPath)) {
    log.warning('.handoff.config.json already exists — not overwriting');
  } else {
    log.info('Creating .handoff.config.json...');
    const version = await getProjectVersion(projectDir);
    const techStack = await detectTechStack(projectDir);
    const config = buildConfig(projectName, version, techStack);
    await writeFile(configPath, JSON.stringify(config, null, 2), 'utf-8');
    log.success('Created .handoff.config.json');
  }
  console.log('');

  // Step 5: Create initial master index with project info
  const masterIndexFilename = `CO-00-MASTER_INDEX_${today}.md`;
  const masterIndexPath = join(handoffDir, masterIndexFilename);

  if (!(await fileExists(masterIndexPath))) {
    log.info(`Creating ${masterIndexFilename}...`);
    const version = await getProjectVersion(projectDir);
    const techStack = await detectTechStack(projectDir);
    const content = generateMasterIndex(projectName, version, techStack, today);
    await writeFile(masterIndexPath, content, 'utf-8');
    log.success(`Created ${masterIndexFilename}`);
  }
  console.log('');

  // Step 6: Print next steps
  log.success('Framework initialization complete!');
  console.log('');
  log.info('Next steps:');
  console.log(`
  1. Fill in TODO placeholders:
     cd ${projectName}/${CANONICAL_DOCS_PATH}

  2. Generate project state:
     npx tsx src/generate-state.mts ${projectName}

  3. Validate naming convention:
     npx tsx src/validate-naming.mts ${projectName}

  4. Run quality gates:
     cd ${projectName} && npx tsc --noEmit && npm run lint && npm run build

  5. Commit:
     cd ${projectName}
     git add ${CANONICAL_DOCS_PATH}/ .handoff.config.json
     git commit -m "docs: initialize handoff framework v${VERSION}"
`);
  log.success('Done!');
}

main().catch((err: Error) => {
  log.error(`Initialization failed: ${err.message}`);
  process.exit(1);
});
