#!/usr/bin/env node --no-warnings
/**
 * init-project.mts — Initialize Handoff Framework in a project
 *
 * Creates docs/handoff-{session}/ with numbered templates, .handoff.config.json,
 * and an initial 00-MASTER_INDEX document.
 *
 * Usage: npx tsx src/init-project.mts <project-name> [--session <slug>]
 * Example: npx tsx src/init-project.mts damieus-com-migration --session 20x-e2e-integration
 * Example: npx tsx src/init-project.mts one4three-co-next-app  (creates docs/handoff/)
 */

import { copyFile, mkdir, writeFile } from 'fs/promises';
import { join } from 'path';

import { VERSION } from './version.js';
import {
  DOC_CATEGORIES,
  DOC_CATEGORY_NAMES,
  DOC_CATEGORY_RANGES,
  buildDocsPath,
  REQUIRED_TEMPLATES,
  RECOMMENDED_TEMPLATES,
  todayISO,
  type HandoffConfig,
} from './types.js';
import {
  log,
  fileExists,
  detectTechStack,
  getProjectVersion,
  getFrameworkRoot,
  resolveProjectDir,
  getHandoffDocsPath,
  parseSessionArg,
} from './utils.js';

// ─── Template Installer ─────────────────────────────────────────

interface CopyResult {
  copied: number;
  skipped: number;
}

async function copyTemplates(
  templatesDir: string,
  handoffDir: string,
  today: string,
): Promise<CopyResult> {
  const allTemplates = [...REQUIRED_TEMPLATES, ...RECOMMENDED_TEMPLATES];
  let copied = 0;
  let skipped = 0;

  for (const tpl of allTemplates) {
    // Template source: templates/v2/CO-00-MASTER_INDEX.md (no date)
    const srcFilename = `${tpl.filename}.md`;
    const srcPath = join(templatesDir, 'v2', srcFilename);

    // Output: docs/handoff/CO-00-MASTER_INDEX_2026-02-20.md (with date)
    const outFilename = `${tpl.filename}_${today}.md`;
    const outPath = join(handoffDir, outFilename);

    if (!(await fileExists(srcPath))) {
      log.dim(`  Template not found: ${srcFilename} — skipping`);
      continue;
    }

    if (await fileExists(outPath)) {
      log.warning(`  File exists: ${outFilename} (skipping)`);
      skipped++;
      continue;
    }

    await copyFile(srcPath, outPath);
    const label = tpl.required ? '🔴' : '🟡';
    log.success(`  ${label} Copied: ${outFilename}`);
    copied++;
  }

  return { copied, skipped };
}

// ─── Config Generator ────────────────────────────────────────────

function buildConfig(
  projectName: string,
  version: string,
  techStack: string[],
  sessionSlug?: string,
): HandoffConfig {
  const today = todayISO();
  const docsPath = buildDocsPath(sessionSlug);

  return {
    projectName,
    version,
    description: '',
    techStack,
    sessionSlug,
    framework: {
      version: VERSION,
      namingVersion: 'v2.1',
      docsPath,
      masterIndexPath: `${docsPath}/00-MASTER_INDEX_${today}.md`,
      tokenBudget: {
        target: 10000,
        warning: 25000,
        critical: 50000,
      },
      autoGenerated: ['01-PROJECT_STATE'],
    },
    qualityGates: {
      typescript: {
        enabled: true,
        command: 'npx tsc --noEmit',
        required: true,
      },
      eslint: {
        enabled: true,
        command: 'npm run lint',
        required: true,
      },
      build: {
        enabled: true,
        command: 'npm run build',
        required: true,
      },
      routeDiscovery: {
        enabled: false,
        command: 'npm run discover:routes',
        artifact: 'e2e/fixtures/route-manifest.json',
        required: false,
      },
      devtools: {
        enabled: techStack.includes('React'),
        command: 'npm run test:devtools',
        required: techStack.includes('React'),
      },
    },
    deployment: {
      requiredGates: ['typescript', 'eslint', 'build'],
      recommendedGates: ['routeDiscovery', 'devtools'],
    },
    tokenEstimates: {},
  };
}

// ─── Master Index Generator ──────────────────────────────────────

function generateMasterIndex(
  projectName: string,
  version: string,
  techStack: string[],
  today: string,
  sessionSlug?: string,
): string {
  const reqRows = REQUIRED_TEMPLATES.map(
    (t) =>
      `| [${t.filename}_${today}.md](${t.filename}_${today}.md) | ${t.description} | ~${t.tokenBudget} | 🔴 MUST READ |`,
  ).join('\n');

  const optRows = RECOMMENDED_TEMPLATES.map(
    (t) =>
      `| [${t.filename}_${today}.md](${t.filename}_${today}.md) | ${t.description} | ~${t.tokenBudget} | 🟡 Recommended |`,
  ).join('\n');

  const sessionLine = sessionSlug ? `\n**Session**: ${sessionSlug}` : '';

  return `# Master Index — ${projectName}

**Project**: ${projectName}
**Version**: ${version}
**Framework**: @dabighomie/handoff-framework v${VERSION}
**Naming Version**: v2.1 (numeric-first)${sessionLine}
**Last Updated**: ${today}

---

## Overview

<!-- INVESTIGATE: Read package.json, README, and recent git log to describe this project -->

**Tech Stack**: ${techStack.join(', ')}
**Status**: <!-- INVESTIGATE: Check deployment config, Vercel/Netlify, or git tags -->

---

## Quick Start (New Agent)

1. Read this file — Navigation hub
2. Read 01 — Current project state & quality gates
3. Read 02 — Critical gotchas and must-know context
4. <!-- INVESTIGATE: What else should a new agent know first? -->

**Estimated read time**: ~5 minutes

---

## Document Index

### Document Groups

| Range | Group | Purpose |
|-------|-------|---------|
${DOC_CATEGORIES.map(
  (c) => {
    const range = DOC_CATEGORY_RANGES[c];
    return `| ${String(range.min).padStart(2, '0')}-${String(range.max).padStart(2, '0')} | ${DOC_CATEGORY_NAMES[c]} | ${REQUIRED_TEMPLATES.find((t) => t.category === c)?.description || RECOMMENDED_TEMPLATES.find((t) => t.category === c)?.description || ''} |`;
  },
).join('\n')}

### Required Documents

| Document | Purpose | Tokens | Priority |
|----------|---------|--------|----------|
${reqRows}

### Recommended Documents

| Document | Purpose | Tokens | Priority |
|----------|---------|--------|----------|
${optRows}

---

## Quality Gates

| Gate | Command | Status |
|------|---------|--------|
| TypeScript | \`npx tsc --noEmit\` | <!-- INVESTIGATE: run the command --> |
| ESLint | \`npm run lint\` | <!-- INVESTIGATE: run the command --> |
| Build | \`npm run build\` | <!-- INVESTIGATE: run the command --> |

---

## Next Steps

<!-- INVESTIGATE: What should an agent work on next? Check issues, PRs, recent commits -->

---

**Framework**: @dabighomie/handoff-framework v${VERSION}
**Generated**: ${today}
`;
}

// ─── Main ────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);
  const { sessionSlug, remainingArgs } = parseSessionArg(rawArgs);
  const projectName = remainingArgs[0];

  if (!projectName) {
    log.error('Project name required');
    console.log('');
    console.log('Usage: npx tsx src/init-project.mts <project-name> [--session <slug>]');
    console.log('Examples:');
    console.log('  npx tsx src/init-project.mts damieus-com-migration --session 20x-e2e-integration');
    console.log('  npx tsx src/init-project.mts one4three-co-next-app');
    process.exit(1);
  }

  const frameworkDir = getFrameworkRoot(import.meta.url);
  const projectDir = resolveProjectDir(frameworkDir, projectName);
  const handoffDir = getHandoffDocsPath(projectDir, sessionSlug);
  const docsPath = buildDocsPath(sessionSlug);
  const today = todayISO();

  const sessionLabel = sessionSlug ? ` (session: ${sessionSlug})` : '';
  log.header(`Initializing Handoff Framework v${VERSION} for: ${projectName}${sessionLabel}`);
  console.log('');

  // Step 1: Verify project exists
  if (!(await fileExists(projectDir))) {
    log.error(`Project directory not found: ${projectDir}`);
    process.exit(1);
  }
  log.success(`Found project: ${projectDir}`);

  // Step 2: Create handoff folder
  if (await fileExists(handoffDir)) {
    log.warning(`${docsPath}/ already exists — will skip existing files`);
  } else {
    await mkdir(handoffDir, { recursive: true });
    log.success(`Created ${docsPath}/`);
  }
  console.log('');

  // Step 3: Copy v2.1 templates
  log.info('Copying numbered templates...');
  const templatesDir = join(frameworkDir, 'templates');
  const { copied, skipped } = await copyTemplates(templatesDir, handoffDir, today);
  log.success(`Copied ${copied} templates, skipped ${skipped} existing`);
  console.log('');

  // Step 4: Create .handoff.config.json
  const configPath = join(projectDir, '.handoff.config.json');

  if (await fileExists(configPath)) {
    log.warning('.handoff.config.json already exists — not overwriting');
  } else {
    log.info('Creating .handoff.config.json...');
    const version = await getProjectVersion(projectDir);
    const techStack = await detectTechStack(projectDir);
    const config = buildConfig(projectName, version, techStack, sessionSlug);
    await writeFile(configPath, JSON.stringify(config, null, 2), 'utf-8');
    log.success('Created .handoff.config.json');
  }
  console.log('');

  // Step 5: Create initial master index with project info
  const masterIndexFilename = `00-MASTER_INDEX_${today}.md`;
  const masterIndexPath = join(handoffDir, masterIndexFilename);

  if (!(await fileExists(masterIndexPath))) {
    log.info(`Creating ${masterIndexFilename}...`);
    const version = await getProjectVersion(projectDir);
    const techStack = await detectTechStack(projectDir);
    const content = generateMasterIndex(projectName, version, techStack, today, sessionSlug);
    await writeFile(masterIndexPath, content, 'utf-8');
    log.success(`Created ${masterIndexFilename}`);
  }
  console.log('');

  // Step 6: Print next steps
  log.success('Framework initialization complete!');
  console.log('');
  const sessionFlag = sessionSlug ? ` --session ${sessionSlug}` : '';
  log.info('Next steps:');
  console.log(`
  1. Investigate the codebase — read source code, run scripts, check git log:
     cd ${projectName}

  2. Generate project state:
     npx tsx src/generate-state.mts ${projectName}${sessionFlag}

  3. Populate templates with findings (not placeholders!):
     cd ${projectName}/${docsPath}

  4. Validate naming convention:
     npx tsx src/validate-naming.mts ${projectName}${sessionFlag}

  5. Run quality gates:
     cd ${projectName} && npx tsc --noEmit && npm run lint && npm run build

  6. Commit:
     cd ${projectName}
     git add ${docsPath}/ .handoff.config.json
     git commit -m "docs: initialize handoff framework v${VERSION}"
`);
  log.success('Done!');
}

main().catch((err: Error) => {
  log.error(`Initialization failed: ${err.message}`);
  process.exit(1);
});
