/**
 * types.ts — Shared TypeScript interfaces for the Handoff Framework
 *
 * All scripts import types from here. Single source of truth for:
 * - Config schema (.handoff.config.json)
 * - Validation results
 * - Template metadata
 * - Document categories (metadata, not filename-based)
 * - Numeric-first naming convention
 */

// ─── Document Categories (metadata inside files, NOT in filenames) ────
export const DOC_CATEGORIES = ['context', 'session', 'findings', 'reference'] as const;
export type DocCategory = typeof DOC_CATEGORIES[number];

export const DOC_CATEGORY_NAMES: Record<DocCategory, string> = {
  context: 'Context',
  session: 'Session',
  findings: 'Findings',
  reference: 'Reference',
};

export const DOC_CATEGORY_DESCRIPTIONS: Record<DocCategory, string> = {
  context: 'Project state, critical context, master index — agent reads first',
  session: 'What happened this session: tasks, log, next steps',
  findings: 'What was discovered: architecture, routes, gaps, tests',
  reference: 'Lookups and tools: file maps, prompts, improvements',
};

/** Numeric ranges define implicit category grouping */
export const DOC_CATEGORY_RANGES: Record<DocCategory, { min: number; max: number }> = {
  context: { min: 0, max: 2 },
  session: { min: 3, max: 5 },
  findings: { min: 6, max: 11 },
  reference: { min: 12, max: 14 },
};

/** Infer category from sequence number */
export function getCategoryForSequence(seq: number): DocCategory {
  if (seq <= 2) return 'context';
  if (seq <= 5) return 'session';
  if (seq <= 11) return 'findings';
  return 'reference';
}

// ─── Legacy FSD Support (for migration from v2.0 → v2.1) ────────
export const FSD_CATEGORIES = ['CO', 'AR', 'OP', 'QA', 'RF'] as const;
export type FsdCategory = typeof FSD_CATEGORIES[number];

export const FSD_CATEGORY_NAMES: Record<FsdCategory, string> = {
  CO: 'Core',
  AR: 'Architecture',
  OP: 'Operations',
  QA: 'Quality',
  RF: 'Reference',
};

/** Legacy regex — matches v2.0 filenames like CO-00-MASTER_INDEX_2026-02-20.md */
export const FSD_FILENAME_REGEX = /^(CO|AR|OP|QA|RF)-(\d{2})-([A-Z][A-Z0-9_]+)_(\d{4}-\d{2}-\d{2})\.md$/;

// ─── Numeric-First Naming (v2.1) ────────────────────────────────

/** Regex for v2.1 filenames: 00-MASTER_INDEX_2026-02-20.md */
export const NUMERIC_FILENAME_REGEX = /^(\d{2})-([A-Z][A-Z0-9_]+)_(\d{4}-\d{2}-\d{2})\.md$/;

/** Base directory for all handoff folders */
export const CANONICAL_DOCS_BASE = 'docs';

/** Prefix for handoff folder names */
export const CANONICAL_DOCS_PREFIX = 'handoff';

/**
 * Build the docs path for a handoff session.
 *
 * With slug:    docs/handoff-20x-e2e-integration
 * Without slug: docs/handoff
 *
 * Real examples from damieus-com-migration:
 *   docs/handoff-20x-e2e-integration/
 *   docs/handoff-checkout-refactor/
 *   docs/handoff-database-migration/
 */
export function buildDocsPath(sessionSlug?: string): string {
  if (!sessionSlug) return `${CANONICAL_DOCS_BASE}/${CANONICAL_DOCS_PREFIX}`;
  const slug = sessionSlug
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return `${CANONICAL_DOCS_BASE}/${CANONICAL_DOCS_PREFIX}-${slug}`;
}

/** @deprecated Use buildDocsPath() instead. Kept for migration compatibility. */
export const CANONICAL_DOCS_PATH = 'docs/handoff';

// ─── Config Schema (.handoff.config.json) ────────────────────────
export interface QualityGateConfig {
  enabled: boolean;
  command: string;
  required: boolean;
  artifact?: string;
}

export interface HandoffConfig {
  projectName: string;
  version: string;
  description?: string;
  techStack: string[];
  repositoryUrl?: string;
  /** Session slug — describes what this handoff covers (e.g. "20x-e2e-integration") */
  sessionSlug?: string;
  framework: {
    version: string;
    namingVersion: 'v2' | 'v2.1';
    /** Resolved folder path (e.g. "docs/handoff-20x-e2e-integration") */
    docsPath: string;
    masterIndexPath: string;
    tokenBudget: {
      target: number;
      warning: number;
      critical: number;
    };
    autoGenerated: string[];
  };
  qualityGates: Record<string, QualityGateConfig>;
  deployment: {
    requiredGates: string[];
    recommendedGates: string[];
  };
  tokenEstimates: Record<string, number>;
}

// ─── Validation Results ──────────────────────────────────────────
export type Severity = 'error' | 'warning' | 'suggestion';

export interface ValidationIssue {
  severity: Severity;
  message: string;
  file?: string;
  line?: number;
  rule?: string;
}

export interface ValidationResult {
  passed: boolean;
  errors: number;
  warnings: number;
  suggestions: number;
  issues: ValidationIssue[];
  score: number; // 0-100
}

// ─── Template Metadata ───────────────────────────────────────────
export interface TemplateMetadata {
  sequence: number;
  slug: string;
  filename: string;
  category: DocCategory;
  required: boolean;
  maxLines: number;
  tokenBudget: number;
  description: string;
}

/**
 * Required docs for every session handoff (v2.1)
 *
 * Ordered by reading priority — an agent scans 00 → 05 first.
 *
 * 00-02: Context  (what do I need to know?)
 * 03-05: Session  (what happened? what's next?)
 */
export const REQUIRED_TEMPLATES: TemplateMetadata[] = [
  {
    sequence: 0,
    slug: 'MASTER_INDEX',
    filename: '00-MASTER_INDEX',
    category: 'context',
    required: true,
    maxLines: 500,
    tokenBudget: 1500,
    description: 'Navigation hub — agent reads first',
  },
  {
    sequence: 1,
    slug: 'PROJECT_STATE',
    filename: '01-PROJECT_STATE',
    category: 'context',
    required: true,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Current snapshot (auto-generated)',
  },
  {
    sequence: 2,
    slug: 'CRITICAL_CONTEXT',
    filename: '02-CRITICAL_CONTEXT',
    category: 'context',
    required: true,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Must-know gotchas, failed commands, blockers',
  },
  {
    sequence: 3,
    slug: 'TASK_TRACKER',
    filename: '03-TASK_TRACKER',
    category: 'session',
    required: true,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'Unified todo — scoreboard, status, action items',
  },
  {
    sequence: 4,
    slug: 'SESSION_LOG',
    filename: '04-SESSION_LOG',
    category: 'session',
    required: true,
    maxLines: 1200,
    tokenBudget: 2500,
    description: 'What was done, skipped, failed, and what\'s outdated',
  },
  {
    sequence: 5,
    slug: 'NEXT_STEPS',
    filename: '05-NEXT_STEPS',
    category: 'session',
    required: true,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'Prioritized actions + deployment roadmap',
  },
];

/**
 * Recommended docs — as needed per session.
 *
 * 06-11: Findings  (what was discovered during investigation)
 * 12-14: Reference (lookups and tools for next agent)
 */
export const RECOMMENDED_TEMPLATES: TemplateMetadata[] = [
  {
    sequence: 6,
    slug: 'ARCHITECTURE',
    filename: '06-ARCHITECTURE',
    category: 'findings',
    required: false,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'System design, data flows, decision records',
  },
  {
    sequence: 7,
    slug: 'COMPONENT_MAP',
    filename: '07-COMPONENT_MAP',
    category: 'findings',
    required: false,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'Component → hook interactions, data flows, blast radius',
  },
  {
    sequence: 8,
    slug: 'ROUTE_AUDIT',
    filename: '08-ROUTE_AUDIT',
    category: 'findings',
    required: false,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'All routes discovered, categorized, revenue-tagged',
  },
  {
    sequence: 9,
    slug: 'GAP_ANALYSIS',
    filename: '09-GAP_ANALYSIS',
    category: 'findings',
    required: false,
    maxLines: 1500,
    tokenBudget: 3000,
    description: 'Comprehensive audit — features, DB, tests, performance',
  },
  {
    sequence: 10,
    slug: 'TEST_FRAMEWORK',
    filename: '10-TEST_FRAMEWORK',
    category: 'findings',
    required: false,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Test-ID conventions, coverage findings, automation',
  },
  {
    sequence: 11,
    slug: 'SCRIPTS_REFERENCE',
    filename: '11-SCRIPTS_REFERENCE',
    category: 'findings',
    required: false,
    maxLines: 800,
    tokenBudget: 1500,
    description: 'All scripts — purpose, usage, status',
  },
  {
    sequence: 12,
    slug: 'REFERENCE_MAP',
    filename: '12-REFERENCE_MAP',
    category: 'reference',
    required: false,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Quick lookup tables for routes, files, features',
  },
  {
    sequence: 13,
    slug: 'AUDIT_PROMPTS',
    filename: '13-AUDIT_PROMPTS',
    category: 'reference',
    required: false,
    maxLines: 1000,
    tokenBudget: 2000,
    description: 'Pre-built prompts for next agent — copy-paste ready',
  },
  {
    sequence: 14,
    slug: 'IMPROVEMENTS',
    filename: '14-IMPROVEMENTS',
    category: 'reference',
    required: false,
    maxLines: 1000,
    tokenBudget: 2000,
    description: 'Instruction files, AGENTS.md, CI/CD, automation',
  },
];

// ─── Project Size Tiers ──────────────────────────────────────────
export type ProjectSize = 'minimal' | 'medium' | 'large';

export const PROJECT_SIZE_THRESHOLDS = {
  minimal: { maxLoc: 5000, requiredDocs: 3, recommendedDocs: 0 },
  medium: { maxLoc: 20000, requiredDocs: 6, recommendedDocs: 2 },
  large: { maxLoc: Infinity, requiredDocs: 6, recommendedDocs: 4 },
} as const;

// ─── Date Utilities ──────────────────────────────────────────────
export function todayISO(): string {
  return new Date().toISOString().split('T')[0];
}

export function isValidISODate(dateStr: string): boolean {
  const regex = /^\d{4}-\d{2}-\d{2}$/;
  if (!regex.test(dateStr)) return false;
  const date = new Date(dateStr + 'T00:00:00Z');
  return !isNaN(date.getTime()) && date.toISOString().startsWith(dateStr);
}
