/**
 * types.ts — Shared TypeScript interfaces for the Handoff Framework
 *
 * All scripts import types from here. Single source of truth for:
 * - Config schema (.handoff.config.json)
 * - Validation results
 * - Template metadata
 * - FSD naming categories
 */

// ─── FSD Categories ──────────────────────────────────────────────
export const FSD_CATEGORIES = ['CO', 'AR', 'OP', 'QA', 'RF'] as const;
export type FsdCategory = typeof FSD_CATEGORIES[number];

export const FSD_CATEGORY_NAMES: Record<FsdCategory, string> = {
  CO: 'Core',
  AR: 'Architecture',
  OP: 'Operations',
  QA: 'Quality',
  RF: 'Reference',
};

export const FSD_CATEGORY_DESCRIPTIONS: Record<FsdCategory, string> = {
  CO: 'Project state, critical context, master index — read first',
  AR: 'System design, data flows, component maps',
  OP: 'Deployment, CI/CD, automation, scripts',
  QA: 'Testing framework, test-IDs, gap analysis',
  RF: 'Route maps, feature status, file lookups',
};

/** Regex for valid FSD filenames: CO-00-MASTER_INDEX_2026-02-20.md */
export const FSD_FILENAME_REGEX = /^(CO|AR|OP|QA|RF)-(\d{2})-([A-Z][A-Z0-9_]+)_(\d{4}-\d{2}-\d{2})\.md$/;

/** Docs must live at this canonical path relative to project root */
export const CANONICAL_DOCS_PATH = 'docs/handoff';

// ─── Config Schema (.handoff.config.json) ────────────────────────
export interface QualityGateConfig {
  enabled: boolean;
  command: string;
  required: boolean;
  artifact?: string;
}

export interface HandoffConfig {
  projectName: string;
  version: string;
  description?: string;
  techStack: string[];
  repositoryUrl?: string;
  framework: {
    version: string;
    namingVersion: 'v1' | 'v2';
    docsPath: string;
    masterIndexPath: string;
    tokenBudget: {
      target: number;
      warning: number;
      critical: number;
    };
    autoGenerated: string[];
  };
  qualityGates: Record<string, QualityGateConfig>;
  deployment: {
    requiredGates: string[];
    recommendedGates: string[];
  };
  tokenEstimates: Record<string, number>;
}

// ─── Validation Results ──────────────────────────────────────────
export type Severity = 'error' | 'warning' | 'suggestion';

export interface ValidationIssue {
  severity: Severity;
  message: string;
  file?: string;
  line?: number;
  rule?: string;
}

export interface ValidationResult {
  passed: boolean;
  errors: number;
  warnings: number;
  suggestions: number;
  issues: ValidationIssue[];
  score: number; // 0-100
}

// ─── Template Metadata ───────────────────────────────────────────
export interface TemplateMetadata {
  category: FsdCategory;
  sequence: number;
  slug: string;
  filename: string;
  required: boolean;
  maxLines: number;
  tokenBudget: number;
  description: string;
}

/** Required docs for every project (v2.0 minimum) */
export const REQUIRED_TEMPLATES: TemplateMetadata[] = [
  {
    category: 'CO',
    sequence: 0,
    slug: 'MASTER_INDEX',
    filename: 'CO-00-MASTER_INDEX',
    required: true,
    maxLines: 500,
    tokenBudget: 1500,
    description: 'Navigation hub — read first',
  },
  {
    category: 'CO',
    sequence: 1,
    slug: 'PROJECT_STATE',
    filename: 'CO-01-PROJECT_STATE',
    required: true,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Current snapshot (auto-generated)',
  },
  {
    category: 'CO',
    sequence: 2,
    slug: 'CRITICAL_CONTEXT',
    filename: 'CO-02-CRITICAL_CONTEXT',
    required: true,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Must-know gotchas, failed commands, issues & recovery',
  },
  {
    category: 'CO',
    sequence: 3,
    slug: 'TASK_TRACKER',
    filename: 'CO-03-TASK_TRACKER',
    required: true,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'Unified todo — scoreboard, status.json, action items, session todos',
  },
  {
    category: 'OP',
    sequence: 1,
    slug: 'DEPLOYMENT_ROADMAP',
    filename: 'OP-01-DEPLOYMENT_ROADMAP',
    required: true,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'How to deploy',
  },
  {
    category: 'QA',
    sequence: 1,
    slug: 'TESTID_FRAMEWORK',
    filename: 'QA-01-TESTID_FRAMEWORK',
    required: true,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Testing standards and test-ID conventions',
  },
];

/** Optional but recommended docs */
export const RECOMMENDED_TEMPLATES: TemplateMetadata[] = [
  {
    category: 'AR',
    sequence: 1,
    slug: 'SYSTEM_ARCHITECTURE',
    filename: 'AR-01-SYSTEM_ARCHITECTURE',
    required: false,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'System architecture and component maps',
  },
  {
    category: 'AR',
    sequence: 2,
    slug: 'COMPONENT_MAP',
    filename: 'AR-02-COMPONENT_MAP',
    required: false,
    maxLines: 1000,
    tokenBudget: 2500,
    description: 'Component → hook interactions, data flows, blast radius',
  },
  {
    category: 'OP',
    sequence: 2,
    slug: 'SESSION_LOG',
    filename: 'OP-02-SESSION_LOG',
    required: false,
    maxLines: 1200,
    tokenBudget: 2500,
    description: 'Completed/skipped/outdated, failed commands, token loss prevention',
  },
  {
    category: 'OP',
    sequence: 3,
    slug: 'SCRIPTS_REFERENCE',
    filename: 'OP-03-SCRIPTS_REFERENCE',
    required: false,
    maxLines: 800,
    tokenBudget: 1500,
    description: 'All scripts — purpose, usage, status',
  },
  {
    category: 'QA',
    sequence: 2,
    slug: 'GAP_ANALYSIS',
    filename: 'QA-02-GAP_ANALYSIS',
    required: false,
    maxLines: 1500,
    tokenBudget: 3000,
    description: 'Comprehensive 20x audit — features, DB, tests, performance',
  },
  {
    category: 'RF',
    sequence: 1,
    slug: 'REFERENCE_MAP',
    filename: 'RF-01-REFERENCE_MAP',
    required: false,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'Quick lookup tables for routes, files, features',
  },
  {
    category: 'RF',
    sequence: 2,
    slug: 'ROUTE_AUDIT',
    filename: 'RF-02-ROUTE_AUDIT',
    required: false,
    maxLines: 800,
    tokenBudget: 2000,
    description: 'All routes discovered, categorized, revenue-tagged',
  },
  {
    category: 'RF',
    sequence: 3,
    slug: 'AUDIT_PROMPTS',
    filename: 'RF-03-AUDIT_PROMPTS',
    required: false,
    maxLines: 1000,
    tokenBudget: 2000,
    description: '20x audit prompts for next agent — copy-paste ready',
  },
  {
    category: 'RF',
    sequence: 4,
    slug: 'IMPROVEMENTS',
    filename: 'RF-04-IMPROVEMENTS',
    required: false,
    maxLines: 1000,
    tokenBudget: 2000,
    description: 'Instruction files, AGENTS.md, CI/CD, automation improvements',
  },
];

// ─── Project Size Tiers ──────────────────────────────────────────
export type ProjectSize = 'minimal' | 'medium' | 'large';

export const PROJECT_SIZE_THRESHOLDS = {
  minimal: { maxLoc: 5000, requiredDocs: 3, recommendedDocs: 0 },
  medium: { maxLoc: 20000, requiredDocs: 5, recommendedDocs: 2 },
  large: { maxLoc: Infinity, requiredDocs: 5, recommendedDocs: 4 },
} as const;

// ─── Date Utilities ──────────────────────────────────────────────
export function todayISO(): string {
  return new Date().toISOString().split('T')[0];
}

export function isValidISODate(dateStr: string): boolean {
  const regex = /^\d{4}-\d{2}-\d{2}$/;
  if (!regex.test(dateStr)) return false;
  const date = new Date(dateStr + 'T00:00:00Z');
  return !isNaN(date.getTime()) && date.toISOString().startsWith(dateStr);
}
